### ISSUE TITLE
US 1: create travel-detail page

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#1]
## Value proposition

As a user
I want to see an overview of my trip. 
So that I can see all important conditions at once.

## Description

![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/c37ce1e9-687c-4591-a55f-7699c8c0d93b)

## Acceptance criteria

- You can see a heading thats called " travel details "   
- An image of the destination ( city )
- A container with the following infos is displayed
- The type of travel / travel-reason
- Name of the city with a red pin icon on the left
- Underneath you can see a Box with two travel information-details displayed 
- The left box contains a person-icon and the names of the members, who join the respective trip
- The right box shows a heading called "time-period"
- The right box displays a time-period 

## Tasks

- [x] create 2 arrays
    - [x] one for the user.data / one for the trip.data
    - [x] both arrays contain two objects
- [x] create a styled.component 
- [x] create a flex-container
    - [x] align the following items "centered" in a column  
    - [x] h1 heading "travel details"
    - [x] create an image-element  
    - [x] add a image of berlin to it
    - [x] create a div-element that contains: 
    - [x] nest a h3-element in it with the value of "travel-reason"
    - [x] nest a p-element with the value of "travel destionation" with a pin-emoji  
- [x] create a grid-container that contains:
    - [x] use styled-components within the js.file to target the container with grid
    - [x] the fr should be arranged as displayed
    - [x] the name.value of "User1"
    - [x] add the icon you see on the wireframe
    - [x] add a h3-element with the text "time-period"
    - [x] import the travel-time-period from the array

## Size
Large
