### ISSUE TITLE
US7: add multiple participants with onKeyPress

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#13]
## Value proposition

As a user
I want to be able to select and deselect multiple participants

## Description

![Image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/cc482d06-f21e-4b41-a063-ac4aafc2d5c4)

## Acceptance criteria

- [x] While entering a participants name, the cursor still focusses on the same input field 
- [x] once the name is entered, it shows up under the field
- [ ] a x symbol allows to delete this person
- [x] only clicking the submit button will submit the form

## Tasks

- [x] use onKeyPress and a prevent Default to prevent pressing the enter key from submitting the form
- [x] let the participant data be stored in a array 
- [x] display the typed array data in a button 
- [ ]  giv this button a delete function

## Size
M

**Comment by mariusgolabski** [comment]
LGTM - one thing I noticed - https://react.dev/reference/react-dom/components/common#common-props - [onKeyPress](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event): A [KeyboardEvent handler](https://react.dev/reference/react-dom/components/common#pointerevent-handler) function. Deprecated. Use onKeyDown or onBeforeInput instead.
