### ISSUE TITLE
US8: adding searchbar to the overview

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#14]
## Value proposition

As a user
I want to quickly find a trip by typing its name into a searchbar

## Description
![Image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/c7db92c2-b95a-4135-ab00-0bc87d4f95f9)

## Acceptance criteria
- [ ] Typing in the searchbar will give suggestions abou the trips that matches the input
- [ ] the results can be clicked

## Tasks
- [ ] target your currentTrip Array to map over it
- [ ] use the onChange even handler on the text field and a function that updates a state every time  the user types something
- [ ] filter the changes and create a new array
- [ ] render the filtered List

## Size
M

**Comment by Faibs7** [comment]
Hey Kevin, you can add that you land on the details page of the trip when you click on it. If that's the case 👍. Looks good to me LGTM
