### ISSUE TITLE
US9: adding the todo manager

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#15]
## Value proposition

As a user, 
I would like to create a new task,
in order to keep my todos organized with regard to a trip 

## Description

![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/77943f2a-0d91-42cc-875b-0909e31a1a58)

## Acceptance criteria
- [ ] The overview shows a amount of tasks if theyre set
- [ ] clicking this button redirected to the task page
- [ ] creating a new task creates an new entry
- [ ] all tasks can be deleted  

## Tasks
- [ ] create a task page
- [ ] build a new component and import useState
- [ ] import the PrimaryLink to redirect to the DetailView
- [ ] updates input value should be rendered in a new box

## Size
M

**Comment by F-Kirchhoff** [comment]
Hey Kevin,
please use links for redirecting to pages, (they can still look like buttons, but we call them links and use "Link" components).
Also, please specify whether the user should be able to toggle the tasks.

If I were you I would split this in 2 stories, one for displaying  and toggling a fixed list of tasks, the second for adding tasks (a third for editing, a fourth for deleting). 

This will give a huge dopamine kick :D

**Comment by KevinKyaterekera** [comment]
Hey Felix, you are right. in this user story only the creating and toggle function should be coded :) editing and deleting will be done in a future US since im needing a edit function anyways :)
