### ISSUE TITLE
US 2: all trips overview-page

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#2]
## Value proposition

As a user
I want to see an overview of all upcoming trips. 
So that i can click on a trip to be redirected to its details-page

## Description
==> Wireframe
![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/7d98f578-2118-4094-bf18-6d6e6e309728)

## Acceptance criteria

- Displayed is a heading with the text " upcoming trips"
    - If there's no event the heading displays "No event planned"
- Under the heading you can select a trip that conains:
    - a picture of the destinated city
    - a title that describes the trip
    - the destinated city with a red pin on its left
- Clicking the box opens the detail-page of its trip

## Tasks

- [ ] create an h1-element with the text "Upcoming events"
- [ ] wirite an if/else statement that displays "Upcoming events" if 
the article-container contains data. if not it displays "No events planned"
- [ ] use an (onClick-) eventListener to render the detail-page
- [ ] use next.js routing and a Link-component
- [ ] create an section-component
    - [ ] use display: grid to arrange the elements properly
    - [ ] use the className attribute " upcomingTrips__container "
    - [ ] store an img element, an h3 element and a p-element in it
- [ ] put the section-component in an article-element
    - [ ] use display: flex-column-center 

## Size
m

**Comment by DorisW3** [comment]
Hi Kevin,

I don't understand why one does only can choose the lower trip. Point three of "both boxes contain:" I would write "the destination with a red pin.." because in the wireframe you show two examples. One has the destination "Holland" and the other "Berlin", so the destination is more unspecific. 
In the task section, you wrote: " Use an (onClick-) eventListener to render the detail page". Maybe think about iterating about the array of objects you want to display.
I like your user story, there are many details and a good amount of tasks! 

P.s. There are some little typing errors;-)

**Comment by KevinKyaterekera** [comment]
hey doris, thanks very much. i guess you're right. maybe i should not use the upper trip, if it isn't ment to be used :) About the onClick i'm not sure, if i get your idea. it should just render the previous page an no new data. guess it just looks much 'cus i did it small-scale :)
