### ISSUE TITLE
US10: edit function

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#20]
## Value proposition
As a user, 
I would like to edit  tasks.    

## Description
![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/e861484d-9a35-467b-b61f-08db55912448)

## Acceptance criteria
- [ ] next to the delete buttons is a button named edit
- [ ] edit button gives option to edit the task  

## Tasks

- [ ] understand the structure of editing a form/input. check mozilla [article](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/React_interactivity_filtering_conditional_rendering) 
- [ ] you wil need, a useState and onChange function

**Comment by izabelladobielewska** [comment]
hey it looks fine, one question: do you think it could be useful to have this function also upon clicking the "open tasks?" (just as in the drawing). If it already is so ignore my question ;)
