### ISSUE TITLE
US11: design

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#21]
## Value proposition

As a user i want to see a inuitive and modern interface

## Description
--> Figma mockup

## Acceptance criteria
- [ ] hover and shadow effects for buttons to be seen
- [ ] proper font sizes and color scheme, as well as icons

## Tasks
- [ ] using the figma mockup file
