### ISSUE TITLE
US 4: creating "NewTripButton" component

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#7]
## Value proposition

As a user
I want to see an icon. 
So that I can create a new trip.

## Description
![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/c6ed7ac8-ad68-447c-b1ef-b841e5695d87)

## Acceptance criteria
- [x] The right bottom corner displays a button with the text: "Add new trip"
- [x] Clicking this button opens a a new window 
- [x] This new window displays "Create your trip" as an heading
    - [x] This page displays the overview-button 

## Tasks
- [x] Create a .js file called "FormPage.js"
- [x] Create a Link component called "NewTripButton"
- [x] Use the Link function to redirect from the Overview to FormPage
- [x] Give this component a button styling

- [x] Place the Button.js component at the FormPage.js

## Size
s

**Comment by ninaassmann** [comment]
better use directly a Link component and style it like a button

**Comment by KevinKyaterekera** [comment]
> better use directly a Link component and style it like a button

hey, thats even better 😎

**Comment by Faibs7** [comment]
Works really good. Keep going. LGTM
