### ISSUE TITLE
US 5: creating FormPage.js

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#8]
## Value proposition

As a user
I want a to be able to create a new trip. 
So that I can set a frame with all necessary conditions,
that are needed to plan a trip.

## Description

![Image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/bbd21e94-3e1e-48b1-959f-678897c635d7)

## Acceptance criteria
- [x] You can see 5 input-fields to specify the travel
- [x] All fields contain placeholders
- [x] Submit-button clears the form

## Tasks

- [x] create a form-element and nest a label-element in it. 
- [x] nest 5 input-elements within the the form-element
- [x] connect the label and input element via "id", and "name" attributes
- [x] adjust the input types according to there function (text, date ..)

- [x] create a button-component with type submit
    - [x] give this component an handleSubmit function to submit the form data

## Size
m

**Comment by ninaassmann** [comment]
- how do you get to this page?
- you need 5 labels and 5 inputs
- what happens after submitting? does it just clear the form or will you write the submit function as well in this US?

**Comment by KevinKyaterekera** [comment]
> * how do you get to this page?
> * you need 5 labels and 5 inputs
> * what happens after submitting? does it just clear the form or will you write the submit function as well in this US?

hey, this page will be reached trough the "create button" in US4, wich includes the Link to this new Page. Yes that is correct. for each input i will connect a label element and the function to create a new element will be build in the next US

**Comment by KilianBau** [comment]
So you just want to create the from in this US? In the acceptance criteria you write that the button clears the form but in your task the button is dumb or what do you mean with onClick function, is that the function which clears the form?

**Comment by KilianBau** [comment]
just explain that a bit more, after that it's a good US 👍

**Comment by KevinKyaterekera** [comment]
> just explain that a bit more, after that it's a good US 👍

Hey, i see. this is a little bit confusing. I want it to have a submit function, so that the form clears, after clicking it. after this, i will focus on creating a new element. but not in this US
