### ISSUE TITLE
US 6: adding trip delete function to overviewpage

### ISSUE THREAD

**Issue by KevinKyaterekera** [KevinKyaterekera/capstone-project#9]
## Value proposition
As a user
I want to see my created trip in my trip overview 
So that i can open or delete my trips

## Description
![image](https://github.com/KevinKyaterekera/capstone-project/assets/125157606/6f44ee87-e430-47f4-89b6-14c3c3644974)

## Acceptance criteria
- [ ] All created trips are displayed
- [ ] Every trip has a button to delete this trip
- [ ] Clicking this button opens a pop up window with the text 
        "You are about to delete this trip. Are your sure?" 
- [ ] There will be two options. "Cancel" and "Ok"
- [ ] If there's no trip left the text "currently no trips planned"
        appears.

## Tasks 
- [ ] create a button component
- [ ] write a handleDelete function and target the id
- [ ] use filter method to filter all trips that dont match with id
- [ ] create a button with an onClick function and pass it the 
   handleDelete function
- [ ] Add an if statement to cancel the delete attempt

## Size
m

**Comment by jonas8900** [comment]
this looks like a good userstory :)! Maybe in you description (picture 2) there's an alert "you are about to...." but there's no way to cancel the delete. Maybe its better to confirm a delete like "bist du dir sicher, dass du deine Reise löschen möchtest?"
